CREATE USER IF NOT EXISTS 'blog_user'@'%' IDENTIFIED BY '123';
GRANT ALL PRIVILEGES ON blog_sport_db.* TO 'blog_user'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    video VARCHAR(900),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
